### ISSUE TITLE
Update tree

### ISSUE THREAD

**Issue by mtskm** [oxyno-zeta/react-editable-json-tree#2]
Ondeltaupdate - results in old value , new value and key modified. What if the same key "test" exists in multiple Json documents ? Is there a way to uniquely find out which one is updated? Also is there an event on selection of a node for update ?

**Comment by oxyno-zeta** [comment]
Hello,
There is the keyPath in the function onDeltaUpdate to know where is the key you are currently editing.
And no, there is no event for selection of the node to update. Can be cool but there is nothing like that for the moment.

**Comment by mtskm** [comment]
Submitted 2 more questions related to is collapsed and search functionality
, please look into that.
