### ISSUE TITLE
Can't resolve 'babel-runtime/core-js/promise'

### ISSUE THREAD

**Issue by lapidus** [oxyno-zeta/react-editable-json-tree#20]
Thank you for a great lib! Seems there's some conflict with babel 7 or a missing dependency. Any help appreciated.

`Module not found: Error: Can't resolve 'babel-runtime/core-js/promise' in '/node_modules/react-editable-json-tree/dist'`

**Comment by crystalv05264** [comment]
add to oringinal 0

**Comment by crystalv05264** [comment]
resolve 'babel-runtime/core-js/promise' in '/node_modules/react-json-

**Comment by Phanabani** [comment]
Closing as this should have been resolved in 2.3.0.
