### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#36]
Hi there!

I worked with you several years ago under the name Hawkpath to add some features to this project! I've just recently come back to use it again, and I've noticed a security vulnerability. Can you [create a security advisory](https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory) and [add me as a collaborator on it](https://docs.github.com/en/code-security/repository-security-advisories/adding-a-collaborator-to-a-repository-security-advisory) so I can discuss this with you? I have a fix prepared, and the security advisory will allow us to work on it privately.

Thanks in advance!

**Comment by oxyno-zeta** [comment]
Hello !

I just published the 2.2.2 version, published the security advisory and requested a CVE.

Thanks for all your work !
