### ISSUE TITLE
Modernizing this project

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#37]
I love this project, but I realized I could not get it to work with modern libraries, so I've been working for a few weeks on updating it! It's not completely ready yet, but I wanted to make an issue so that you're aware and can wait for my changes in case you were for any reason thinking of doing this yourself.

In my [change/update-all](https://github.com/Phanabani/react-editable-json-tree/tree/change/update-all) branch, I have:
- Updated dependencies to their latest versions
- Removed/replaced a lot of deprecated libraries
- Added Typescript support
- Added Prettier support for automatic formatting
- Rewritten gulp tasks in typescript with gulp's new task export API
- Updated various babel things
- Rewritten webpack configuration files in typescript and fixed deprecations in them (this was very difficult and it might not be 100% perfect, but it appears to be working well!)
- Rewritten the `/dev` test page in typescript as functional React components

This branch is fully functional and the component seems to be working as intended on current versions of Node and npm. You might opt to pull this branch now so that people on modern setups can begin using/update this component. You should wait until #36 is resolved before doing that though for security reasons.

Additionally, I am rewriting the core components in typescript as functional components that use React hooks, migrating from class components, since this appears to be the preferred way forward for React components. I'm also working on refactoring some things, like using context and reducers to avoid having to pass lots of props down the tree. You can see my work in my [change/modernize-core](https://github.com/Phanabani/react-editable-json-tree/tree/change/modernize-core) branch.

I'm hoping that this will allow more people to use this project and make it easier for potential updates in the future! I will do a pull request when I'm done so you can check it out for yourself and see if this is something you would like to merge.

**Comment by Phanabani** [comment]
Also, one extra note -- I've been removing your organizational comments that look like:
```js
/* ************************************* */
/* ********      COMPONENT      ******** */
/* ************************************* */
```
I hope you don't mind! I don't want to disrespect the hard work you've done to organize. I just noticed that they were getting in the way of automatic IDE functions like formatting and adding imports and stuff like that. I can add them back when I'm done if it's important to you!

I also have not changed the comments at the tops of each file that have author, date, and license, and did not add them to new code I've written because I think the git logs already contain info like that if someone needed it. Feel free to let me know your thoughts on this as well.

**Comment by oxyno-zeta** [comment]
Hello @Phanabani ,

I must admit that I didn't work on this for a while ! I wasn't thinking that someone will be ping me on it.

You can remove all comments you wanted. You can also remove the gulp if you want (I was thinking long time ago of using parcel for the build and a cra for the demo).
Maybe another point will be to switch to Function components and hooks but that's another story.

I will be happy to see your Pull Request with all of this.
