### ISSUE TITLE
How to expand or collapse tree based on a condition in a data?

### ISSUE THREAD

**Issue by mtskm** [oxyno-zeta/react-editable-json-tree#4]

**Comment by oxyno-zeta** [comment]
Hello,

There is a props named: isCollapse that can help you for that. You can choose what you want to expand programmatically. All parameters are explained in the README. 

Oxyno-zeta

**Comment by mtskm** [comment]
IsCollapse props takes deep as a paramter with which looks like there is only possibility of expand or collapse with respect to depth of the tree. Do you have any example for this in repository?

**Comment by oxyno-zeta** [comment]
No sorry. I haven't any example of this.

**Comment by mtskm** [comment]
But there is no data parameter currently supported in isCollapse property.

**Comment by mtskm** [comment]
Thank you for adding name and data, keep me posted.

**Comment by oxyno-zeta** [comment]
The new version is released.
I just added data. Name is already added in the keyPath (the last item).
