### ISSUE TITLE
Add Github project for v3.0.0

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#44]
Hey @oxyno-zeta!

In my personal repos, I've used [Github projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) to manage versions. If you haven't used them, they're essentially kanban boards. I invited you to a project I created named "React Editable JSON Tree v3.0.0", but I need you to add it to this repo since I don't have admin privileges. If you could do that I'd be super grateful! It would help me keep track of the changes I plan to make and my progress on them.

![image](https://user-images.githubusercontent.com/26840888/189249578-907ab132-8197-4982-8c28-5742fe138968.png)

**Comment by oxyno-zeta** [comment]
Hello @Phanabani !

Sure ! I know them but I never used them since I'm a fan of TODO.md 😁.
I will create it for you.

I'm keeping this open to discuss on this if you need something else.

Oxyno-zeta

**Comment by Phanabani** [comment]
Ooh, the TODO.md is pretty good. I'm a frequent user of the "keeping everything in my brain" approach 🤣. Thank you for doing this for me!
