### ISSUE TITLE
CircleCI permission denied error

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#49]
Hey @oxyno-zeta!

I'm just about ready to release v2.3.0. The last issue I'm working on, #42, ran into a problem that I need your help for.

I've updated the CircleCI config, but the [build failed with the reason: "Permission denied (publickey)"](https://app.circleci.com/pipelines/github/oxyno-zeta/react-editable-json-tree/28/workflows/ac058720-98b2-404a-a9c9-77286ebdc64a/jobs/93/steps?invite=true#step-101-75). I think you need to generate a new [GitHub deploy key](https://circleci.com/docs/github-integration/#create-a-github-deploy-key). This answer [here](https://discuss.circleci.com/t/git-github-com-permission-denied-publickey-on-repo-that-previously-worked/37763/5) seems to give a simpler summary of what you need to do.

I'm not 100% sure if this is the issue, but I don't have the permissions to investigate further, so I need your help whenever you're available! Hopefully this will fix the problem and I can finish up. :)

**Comment by oxyno-zeta** [comment]
Hello,

I removed and added back another key. Tell me if it is working now.

Regards,

Oxyno-zeta

**Comment by oxyno-zeta** [comment]
After checking deeper, I think the configuration for CircleCI isn't working anymore. Maybe it is time to switch to Github CI. What do you think of this ?

**Comment by Phanabani** [comment]
@oxyno-zeta [I got it to succeed!](https://app.circleci.com/pipelines/github/oxyno-zeta/react-editable-json-tree/36/workflows/70796ba9-c215-47e4-af93-ee7291ef9099/jobs/96)

Do you still want to transition to Github CI, or is it okay to remain with Circle?

**Comment by oxyno-zeta** [comment]
Oh for me it is ok to remain on circle. Was thinking doing it from scratch may be easier on GitHub but I'm ok to stay on Circle if you prefer.

**Comment by oxyno-zeta** [comment]
Maybe because your release branch is on your fork ? I don't remember if it was accepted to build forks...

**Comment by Phanabani** [comment]
Hmm, I'm not sure because my branches are on your repo, not my fork. 🤔

I'm going to merge the Circle config update into release/2.3.0, but I'll try implementing the Github CI on another branch to see if it's easier!
