### ISSUE TITLE
Fix npm publish task missing

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#50]
We need a way to generate a tar file for npm!

**Comment by Phanabani** [comment]
@oxyno-zeta 

I added a prepack script to build the library before packing/publishing in 7c5fbb46fd56ad12bdd8e957e7aa056f5ba073fd. I tested that it worked with `npm pack` and saw the dist files are included in the generated tarball. I think that solves [the problem you mentioned](https://github.com/oxyno-zeta/react-editable-json-tree/pull/48#issuecomment-1271121699) in the pull request, right?

**Comment by oxyno-zeta** [comment]
Oh ... If it is just a "build" to perform. Maybe just a line in the readme on how to release will be enough. May be better by the way. What do think?

**Comment by Phanabani** [comment]
Oh, I was just looking at the npm lifecycle scripts, and it looks like [`npm publish`](https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-publish) already uses my `prepublishOnly` script, which does the build. I don't think prepack is necessary so I'm going to remove it. Yes, I'll add a line in the readme!

**Comment by Phanabani** [comment]
Done! I tested with a private local npm repository ([verdaccio](https://verdaccio.org/)) and it works correctly.
