### ISSUE TITLE
Use GitHub actions for CI?

### ISSUE THREAD

**Issue by Phanabani** [oxyno-zeta/react-editable-json-tree#51]
Hey @oxyno-zeta!

Following our discussion in #49, I've added a [GitHub action](https://github.com/oxyno-zeta/react-editable-json-tree/blob/change/use-github-actions/.github/workflows/node.js.yml) in [change/use-github-actions](https://github.com/oxyno-zeta/react-editable-json-tree/tree/change/use-github-actions) to test builds, rather than using CircleCI. [Here is the successful result of the action.](https://github.com/oxyno-zeta/react-editable-json-tree/actions/runs/3228152615/jobs/5283874356)

Would you like for me to merge this into 2.3.0, using GitHub actions for CI instead of Circle?

If yes, I'll just need you to remove Circle from tracking this repo so we don't see its failed attempted builds!

**Comment by oxyno-zeta** [comment]
Hello,

You can ! That's not a requirement for me in itself. The only requirement was to have a CI working ! :) 
You did it well on 2.3.0 branch.
As you want ! ;)

Regards,

Oxyno-zeta

**Comment by Phanabani** [comment]
I will use GitHub actions! Gonna merge it into 2.3.0 😊
