### ISSUE TITLE
Error when changing values in array

### ISSUE THREAD

**Issue by Hawkpath** [oxyno-zeta/react-editable-json-tree#6]
Hello! I love your module, and I've been using it all weekend. I just found out that when I try to directly change a value in an array, I get an error: `TypeError: handleUpdateValue(...) is undefined`. This originates from line 178 in ./components/JsonValue.js. This causes the value to change (`onDeltaUpdate` gets called, but not `beforeUpdateAction`), but the input box doesn't close. I tried it in Firefox on Linux, and Chrome on Windows (using your demo website) and got the same error each time.

One thing that might help is that if there is an object inside an array, I can edit that object's properties without this error occurring. Only values directly inside the array seem to cause it.

**Comment by oxyno-zeta** [comment]
Hello !

Thanks to use this library :).
I see the bug on the demo page. I will fix this this night (I can't for the moment...).

Oxyno-zeta

**Comment by oxyno-zeta** [comment]
I've just released the 2.1.0 version.
This version should fix the bug. I've also added a new feature to log errors on promises.

Can you tell me if it is ok ?

**Comment by Hawkpath** [comment]
Yes, it's working well now! Thanks a lot for your help and the excellent library. I'll let you know if I happen to find any other bugs.

**Comment by oxyno-zeta** [comment]
That's a good news !
You are welcome.
Thanks for using library and to create these bugs. This improve library ;-). Don't hesitate !
