### ISSUE TITLE
inputElement Improvement Suggestion

### ISSUE THREAD

**Issue by Hawkpath** [oxyno-zeta/react-editable-json-tree#7]
Hello again! I've gotten an idea for an improvement to your library.

Currently, you have the `inputElement` prop which is used to globally define the element used to edit values. I really like how you've implemented `getStyle` and `readOnly`, and I thought it would be useful to have similar functionality for `inputElement` -- pass it as a function which receives the parameters `keyName, data, keyPath, deep, dataType` and returns an input element. It probably wouldn't be difficult to maintain backward compatibility like this, either.

The reason I think this change would be helpful is that you can have special handlers for specific types of data (such as numbers, dates, and times). Personally, I would like this so that I could display toggle buttons to change boolean values by clicking instead of having to type "true"/"false".

I'd like to hear what you think about this!

**Comment by oxyno-zeta** [comment]
Hello,

Good issue. This will be great !
I will see how to do it :).

Thanks !

Oxyno-zeta

**Comment by oxyno-zeta** [comment]
@Hawkpath After a small research, this can be done on the edit mode. The problem is on the add mode. Datatype will be 'undefined'. 

I won't implement it today. I must think more about this point. If you have an idea, don't hesitate ;-)

Oxyno-zeta

**Comment by Hawkpath** [comment]
Thanks for looking into this!

So, the problem you're thinking about is that when you are adding a new item with the + button, there is no `dataType`, `keyName`, or `data` to pass to the `inputElement` function? I can see how that would be an issue since receiving 'Undefined' as the `dataType` here does not mean the literal `undefined` type.

Perhaps you could add a new property, such as `addInputElement`, in addition to `inputElement`? This would define the input for add mode separately from the one for edit mode. For this prop, you might be able to skip the need to accept a function like my proposal for `inputElement` because it may not be necessary/plausible to have different inputs for adding a new item. However, one case where I can imagine it working is if there was an array of dates. The `addInputElement` function could receive the `path` to the parent object, and since the user knew this path would contain only dates, he could program it to return a date picker input. I don't know how useful that would be, but it's certainly a possibility to consider.

**Comment by oxyno-zeta** [comment]
I see the possibilty you exposed. In fact, this can be really great.

Another problem in on the textareaElement :).
Why a function on input and not on textarea ? This could be possible but need to be explained :). I will see for this point.

A possibility can be:
* Keep inputElement for add and edit
* Function can have parameters: `keyPath, deep, keyName, data, dataType`
** On edit: all have values
** On add: only `keyPath` and `deep` have values
* TextareaElement can have the same behaviour

@Hawkpath : Do you see something wrong ?

(Sorry for this late explanation, it is late here and hard day...)

**Comment by oxyno-zeta** [comment]
@Hawkpath :

I think there is a misunderstood.

A possibility can be:

* Keep inputElement for add and edit
* Function can have parameters: keyPath, deep, keyName, data, dataType
* * On edit: all have values
* * * On `undefined` value, this will take : [], 0, "test", undefined, "Undefined"
* * On add: only keyPath and deep have values, all other will take undefined
* * * This will take : [], 0, undefined, undefined, undefined
* TextareaElement can have the same behaviour

So you are in the add case when dataType is `undefined` and in edit mode dataType is always valorised as a string. So you can just switch on this no ? This can be good like that and all case are solved.
I can't get the keyName when you are in the add case. Only in edit mode.

For your second question, I've edited the example you give me. See https://pastebin.com/YpmfKMwt
But next time, a new issue will be better. If you have an answer on my example, please create a new issue to have better lisibility :). Thanks !

For this issue and your question, I was thinking of providing a way to give the parse function you want to execute (used on onClick event for add/edit). For the moment, it is only mine but you may want to change it.

**Comment by oxyno-zeta** [comment]
Hello,

I've just released the 2.2.0 with new features.
I think the subject can be closed, no ?

Oxyno-zeta

PS: Thanks for the idea :)

**Comment by Hawkpath** [comment]
@oxyno-zeta 

I'm glad we figured it all out. The morning coffee is the true hero here! Haha :D
I'm excited to try everything out tomorrow. Thank you for adding these new features. I'll let you know if I find any bugs!

Also, thanks for the help with the other problem I mentioned. I'll be sure to make a separate issue next time instead of adding on to an existing one :P. I hadn't read about Javascript's getter/setter syntax yet, so I'm glad I've learned it now.

**Comment by oxyno-zeta** [comment]
@Hawkpath 
Thanks to you for the improvement. Yes don't hesitate if you find some bugs. I will try to fix them quickly.

No problem for the second part. The getter/setter syntax comes with class. Just have a read of get/set in JavaScript class. You will understand quickly ;-).

Also thanks to you for using, improving and following issues !
