### ISSUE TITLE
Value of Deep

### ISSUE THREAD

**Issue by cgvedant** [oxyno-zeta/react-editable-json-tree#8]
Hi, I have a question about how we define the deep value of a node. Considering the example`data={x: "a string value", y: {z: "y is an object"}};` I expected x and y to have the same deep. But y, being an object, gets the value [deep + 1](https://github.com/oxyno-zeta/react-editable-json-tree/blob/master/src/components/JsonObject.js#L59). Is this a bug, if not could you please help me understand why you chose this design.

**Comment by oxyno-zeta** [comment]
Hello,

I can confirm that there is a problem on deep calculation... As said previously, readOnly has the trouble. 
Can you provide the example you have please ? And confirm that this is only on readOnly function that the problem appears ?

Thanks !

**Comment by cgvedant** [comment]
Yes, I've noticed the problem when trying to print deep inside the function passed as readOnly. My example is pretty similar to the one I've gicen aboe, except that y is an empty array
`{
        id: 'newId',
        description: 'New description.',
        owner: 'new-owner-group@email.com',
        featureSpecs: [],
        scorerSpecs: [],
      }`
Hope this helps

**Comment by oxyno-zeta** [comment]
Hello,

Ok. I just wanted to know if the readOnly function was the only one that have this bug :).
I've committed the fix. I will release the new version soon. (Tomorrow I think).

**Comment by oxyno-zeta** [comment]
I've just published the 2.2.1 with the fix. Can you tell me if it is correct now ? It should be, but I prefer your confirmation :).

**Comment by cgvedant** [comment]
Yes, the error seems to be fixed!

**Comment by oxyno-zeta** [comment]
Cool :). Happy to see that !
